### Causal inference

Causal inference is an important topic for the social sciences and I maybe you have learned that a correlation does not imply causation. As the scatter plot on the right side illustrates, there might be a strong association between X and Y, but this does not mean and X is a cause for Y, because a common cause may induce a correlation between those variables. They may not be correlated at all if we estimate the effect depending on the third variable. We speak about a *confounding variable* that affects X and Y. Controlling for a confounder is a common approach in the social sciences and this dashboards illustrates why we must control for confounding variables to estimate the true effect of X on Y.

However, the same does not apply to mediator and collider variables and to control a collider variable may induce an correlation that otherwise does not exist. This sounds probably vague, but you will see that it means with this dashboard as well.

[The source code of this app is available on my github account.](https://github.com/edgar-treischl/Power-App)
